services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: aries
      POSTGRES_PASSWORD: aries
      POSTGRES_DB: aries_case_study
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
